[build]
  command = "npm install && npm run build"
  publish = "out"

[functions]
  directory = ""

[dev]
  command = "npm run dev"
  port = 8888
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
